name: Dev Workflow

on:
  workflow_dispatch: # Manual trigger for the workflow
  push:
    branches:
      - dev # Change this to your branch name if needed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH key for accessing EC2
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_SECRET_KEY_DEV }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Step 3: Set up known hosts to avoid SSH prompts
      - name: Set up known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_IP_DEV }} >> ~/.ssh/known_hosts

      # Step 4: Copy project files to the server
      - name: Copy project files to server
        run: |
          scp -r -i ~/.ssh/id_rsa . ec2-user@${{ secrets.EC2_IP_DEV }}:/tmp/nextjs_project

      # Step 5: Build the Next.js app on the server
      - name: Build Next.js app on server
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_IP_DEV }} << EOF
            cd /tmp/nextjs_project
            npm install
            npm run build
            sudo cp -r ./out/* /usr/share/nginx/html/
          EOF

      # Step 6: Reload Nginx to apply changes
      - name: Reload Nginx
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_IP_DEV }} 'sudo systemctl reload nginx'
