name: DEV Workflow

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH key for accessing EC2
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_SECRET_KEY_DEV }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Step 3: Set up known hosts to avoid SSH prompts
      - name: Set up known hosts
        run: |
          if [ -z "${{ secrets.EC2_IP_DEV }}" ]; then
            echo "Error: EC2_IP_DEV is not set."
            exit 1
          fi
          ssh-keyscan -H ${{ secrets.EC2_IP_DEV }} >> ~/.ssh/known_hosts

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 5: Build the Next.js app
      - name: Build Next.js app
        run: |
          npm run build

      # Step 6: Deploy files to the Nginx server
      - name: Copy files to Nginx server
        run: |
          scp -r -i ~/.ssh/id_rsa ./out/* ec2-user@${{ secrets.EC2_IP_DEV }}:/usr/share/nginx/html/

      # Step 7: Reload Nginx to apply changes
      - name: Reload Nginx
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_IP_DEV }} 'sudo systemctl reload nginx'
